# Generated by Django 5.1.7 on 2025-03-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="is_completes",
            new_name="is_completed",
        ),
    ]
