# Generated by Django 5.1.7 on 2025-03-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_rename_is_completes_todo_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="important",
            field=models.BooleanField(default=False),
        ),
    ]
